export enum API_ERROR_CODES {
	ACCOUNT_ALREADY_EXISTS = '@ACCOUNT_ALREADY_EXISTS',
	INVALID_TOKEN = '@INVALID_TOKEN',
	UNAUTHORIZED_ACCESS_TOKEN = '@UNAUTHORIZED_ACCESS_TOKEN',
	EXPIRED_ACCESS_TOKEN = '@EXPIRED_ACCESS_TOKEN',
	WRONG_CODE = '@WRONG_CODE',
	USER_NOT_FOUND = '@USER_NOT_FOUND',
	EXPIRED_TOKEN = '@EXPIRED_TOKEN',
	INVALID_CODE = '@INVALID_CODE',

	// Habits
	HABIT_NOT_FOUND = '@HABIT_NOT_FOUND',
	HABIT_ALREADY_EXISTS = '@HABIT_ALREADY_EXISTS',
	INVALID_HABIT_DATA = '@INVALID_HABIT_DATA',
	HABIT_PROGRESS_ALREADY_RECORDED_TODAY = '@HABIT_PROGRESS_ALREADY_RECORDED_TODAY',
	INVALID_WEEKDAY = '@INVALID_WEEKDAY',
	HABIT_DELETION_FAILED = '@HABIT_DELETION_FAILED',

	// Analytics
	INSUFFICIENT_DATA_FOR_ANALYTICS = '@INSUFFICIENT_DATA_FOR_ANALYTICS',
	ANALYTICS_CALCULATION_ERROR = '@ANALYTICS_CALCULATION_ERROR',

	// User Profile
	PROFILE_NOT_FOUND = '@PROFILE_NOT_FOUND',
	PROFILE_UPDATE_FAILED = '@PROFILE_UPDATE_FAILED',
	ROLE_NOT_FOUND = '@ROLE_NOT_FOUND',

	// Goals
	GOAL_NOT_FOUND = '@GOAL_NOT_FOUND',
	GOAL_ALREADY_EXISTS = '@GOAL_ALREADY_EXISTS',
	INVALID_GOAL_DATA = '@INVALID_GOAL_DATA',
	GOAL_CREATION_FAILED = '@GOAL_CREATION_FAILED',
	GOAL_UPDATE_FAILED = '@GOAL_UPDATE_FAILED',
	GOAL_DELETION_FAILED = '@GOAL_DELETION_FAILED',
	GOAL_DATE_CONFLICT = '@GOAL_DATE_CONFLICT',
	GOAL_TARGET_INVALID = '@GOAL_TARGET_INVALID',

	// Achievements
	ACHIEVEMENT_NOT_FOUND = '@ACHIEVEMENT_NOT_FOUND',
	ACHIEVEMENT_ALREADY_UNLOCKED = '@ACHIEVEMENT_ALREADY_UNLOCKED',
	ACHIEVEMENT_UNLOCK_FAILED = '@ACHIEVEMENT_UNLOCK_FAILED',
	ACHIEVEMENT_CONDITIONS_NOT_MET = '@ACHIEVEMENT_CONDITIONS_NOT_MET',
	INVALID_ACHIEVEMENT_TYPE = '@INVALID_ACHIEVEMENT_TYPE',

	// Reports
	REPORT_GENERATION_FAILED = '@REPORT_GENERATION_FAILED',
	INSUFFICIENT_DATA_FOR_REPORT = '@INSUFFICIENT_DATA_FOR_REPORT',
	INVALID_REPORT_PERIOD = '@INVALID_REPORT_PERIOD',
	REPORT_EXPORT_FAILED = '@REPORT_EXPORT_FAILED',

	// Notifications
	NOTIFICATION_SEND_FAILED = '@NOTIFICATION_SEND_FAILED',
	NOTIFICATION_NOT_FOUND = '@NOTIFICATION_NOT_FOUND',
	NOTIFICATION_ALREADY_SENT = '@NOTIFICATION_ALREADY_SENT',
	INVALID_NOTIFICATION_TYPE = '@INVALID_NOTIFICATION_TYPE',
	NOTIFICATION_PREFERENCES_NOT_FOUND = '@NOTIFICATION_PREFERENCES_NOT_FOUND',
	NOTIFICATION_PREFERENCES_UPDATE_FAILED = '@NOTIFICATION_PREFERENCES_UPDATE_FAILED',
	DEVICE_REGISTRATION_FAILED = '@DEVICE_REGISTRATION_FAILED',
	DEVICE_NOT_FOUND = '@DEVICE_NOT_FOUND',
	DEVICE_ALREADY_REGISTERED = '@DEVICE_ALREADY_REGISTERED',
	INVALID_DEVICE_TOKEN = '@INVALID_DEVICE_TOKEN',
	NOTIFICATION_PROVIDER_ERROR = '@NOTIFICATION_PROVIDER_ERROR',
	NOTIFICATION_TEMPLATE_NOT_FOUND = '@NOTIFICATION_TEMPLATE_NOT_FOUND',
	NOTIFICATION_RATE_LIMIT_EXCEEDED = '@NOTIFICATION_RATE_LIMIT_EXCEEDED',
}
