export enum API_ERROR_CODES {
	ACCOUNT_ALREADY_EXISTS = '@ACCOUNT_ALREADY_EXISTS',
	INVALID_TOKEN = '@INVALID_TOKEN',
	UNAUTHORIZED_ACCESS_TOKEN = '@UNAUTHORIZED_ACCESS_TOKEN',
	EXPIRED_ACCESS_TOKEN = '@EXPIRED_ACCESS_TOKEN',
	WRONG_CODE = '@WRONG_CODE',
	USER_NOT_FOUND = '@USER_NOT_FOUND',
	EXPIRED_TOKEN = '@EXPIRED_TOKEN',
	INVALID_CODE = '@INVALID_CODE',

	// Habits
	HABIT_NOT_FOUND = '@HABIT_NOT_FOUND',
	HABIT_ALREADY_EXISTS = '@HABIT_ALREADY_EXISTS',
	INVALID_HABIT_DATA = '@INVALID_HABIT_DATA',
	HABIT_PROGRESS_ALREADY_RECORDED_TODAY = '@HABIT_PROGRESS_ALREADY_RECORDED_TODAY',
	INVALID_WEEKDAY = '@INVALID_WEEKDAY',
	HABIT_DELETION_FAILED = '@HABIT_DELETION_FAILED',

	// Analytics
	INSUFFICIENT_DATA_FOR_ANALYTICS = '@INSUFFICIENT_DATA_FOR_ANALYTICS',
	ANALYTICS_CALCULATION_ERROR = '@ANALYTICS_CALCULATION_ERROR',

	// User Profile
	PROFILE_NOT_FOUND = '@PROFILE_NOT_FOUND',
	PROFILE_UPDATE_FAILED = '@PROFILE_UPDATE_FAILED',
}
