export enum API_SUCCESS_CODES {
	SERVER_IS_RUNNING = '@SERVER_IS_RUNNING',
	ACCOUNT_CREATED_SUCCESSFULY = '@ACCOUNT_CREATED_SUCCESSFULY',
	LOGGED_IN_SUCCESSFULY = '@LOGGED_IN_SUCCESSFULY',
	LOGGED_OUT_SUCCESSFULY = '@LOGGED_OUT_SUCCESSFULY',
	EMAIL_CONFIRMED = '@EMAIL_CONFIRMED',
	EMAIL_RESENT = '@EMAIL_RESENT',
	USER_FOUND = '@USER_FOUND',
	TOKEN_REFRESHED = '@TOKEN_REFRESHED',
	PASSWORD_RESETED = '@PASSWORD_RESETED',
}
