export enum API_SUCCESS_CODES {
	SERVER_IS_RUNNING = '@SERVER_IS_RUNNING',
	ACCOUNT_CREATED_SUCCESSFULY = '@ACCOUNT_CREATED_SUCCESSFULY',
	LOGGED_IN_SUCCESSFULY = '@LOGGED_IN_SUCCESSFULY',
	EMAIL_CONFIRMED = '@EMAIL_CONFIRMED',
	EMAIL_RESENT = '@EMAIL_RESENT',
}
