export enum API_SUCCESS_CODES {
	SERVER_IS_RUNNING = '@SERVER_IS_RUNNING',
	ACCOUNT_CREATED_SUCCESSFULY = '@ACCOUNT_CREATED_SUCCESSFULY',
	LOGGED_IN_SUCCESSFULY = '@LOGGED_IN_SUCCESSFULY',
	LOGGED_OUT_SUCCESSFULY = '@LOGGED_OUT_SUCCESSFULY',
	EMAIL_CONFIRMED = '@EMAIL_CONFIRMED',
	EMAIL_RESENT = '@EMAIL_RESENT',
	USER_FOUND = '@USER_FOUND',
	TOKEN_REFRESHED = '@TOKEN_REFRESHED',
	PASSWORD_RESETED = '@PASSWORD_RESETED',

	// Habits
	HABIT_CREATED_SUCCESSFULLY = '@HABIT_CREATED_SUCCESSFULLY',
	HABIT_UPDATED_SUCCESSFULLY = '@HABIT_UPDATED_SUCCESSFULLY',
	HABIT_DELETED_SUCCESSFULLY = '@HABIT_DELETED_SUCCESSFULLY',
	HABIT_FOUND = '@HABIT_FOUND',
	HABITS_FOUND = '@HABITS_FOUND',
	HABIT_PROGRESS_RECORDED = '@HABIT_PROGRESS_RECORDED',
	HABIT_PROGRESS_FOUND = '@HABIT_PROGRESS_FOUND',

	// Analytics
	DASHBOARD_DATA_FOUND = '@DASHBOARD_DATA_FOUND',
	STREAKS_DATA_FOUND = '@STREAKS_DATA_FOUND',
	ANALYTICS_GENERATED_SUCCESSFULLY = '@ANALYTICS_GENERATED_SUCCESSFULLY',

	// User Profile
	PROFILE_UPDATED_SUCCESSFULLY = '@PROFILE_UPDATED_SUCCESSFULLY',
}
