#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Temporarily disabled due to Windows compatibility issues
# npm run lint
# npm run format
echo "Pre-commit hook executed successfully"
# yarn test:cov
